version: '3'
services:
  api:
    build: ./app
    command: python main.py
    container_name: api
    expose:
      - 5000
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    networks:
      - app_nw
    environment:
      FLASK_APP: main.py
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_DEBUG: True
    restart: always

  web:
    build: ./web
    container_name: web
    command: npm start
    expose:
      - 3000
    ports:
      - 3000:3000
    networks:
      - app_nw
    restart: always
    

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    container_name: nginx
    restart: always
    networks:
      - app_nw
    depends_on:
      - api
      - web
    

networks:
  app_nw:
    driver: bridge